name: "gemma"
version: 1.0
size: "2B"
model_name: "google/gemma-2b"
model_it_name: "google/gemma-2b-it"
model_max_new_tokens: 100


model_spec:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${models.gemma.model_name}

tokenizer_spec:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${models.gemma.model_name}
