name: "llama"
version: 3.2
size: "1B"
model_name: "meta-llama/Llama-3.2-1B"
model_it_name: "meta-llama/Llama-3.2-1B-Instruct"
model_max_new_tokens: 100

model_spec:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${models.llama3.model_name}

tokenizer_spec:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${models.llama3.model_name}
