name: "OPT"
version: 1.0
size: "125M"
model_name: "facebook/opt-125m"
model_it_name: "facebook/opt-125m"

model_spec:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${models.opt.model_name}

tokenizer_spec:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${models.opt.model_name}
