name: "svamp"
huggingface_dataset_id: "ChilleD/SVAMP"

answer_key: "Answer"
question_key: "Question"
answerable_only: True

spec:
  _target_: datasets.load_dataset
  path: ${dataset.huggingface_dataset_id}
  split: train
