compute_predictive_entropy: True
entailment_model: "deberta"
use_all_generations: True
recompute_accuracy: False
compute_context_entails_response: True
condition_on_question: True
strict_entailment: True
compute_p_true_in_compute_stage: False
num_eval_samples: 1
compute_p_ik: False
compute_p_ik_answerable: False
analyze_run: True