entropy_type: "oatml"
compute_predictive_entropy: True
entailment_model: "deberta"
use_all_generations: True
recompute_accuracy: False
compute_context_entails_response: True
condition_on_question: True
strict_entailment: True
compute_p_true_in_compute_stage: False
num_eval_samples: 1
compute_p_ik: False
compute_p_ik_answerable: False
analyze_run: True
collect_generations:
  _target_: src.oatml_generations.collect_generations
compute_uncertainty_measures_for_generations:
  _target_: src.oatml_generations.compute_uncertainty_measures_for_generations
analyse_generations:
  _target_: src.oatml_generations.analyse_generations
eval_function:
  _target_: src.utils.oatml_ensemble